services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: solati_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
